"""Closed additive continuation policy; execution requires separate adoption."""

from hashlib import sha256

from . import _study_execution_policy as original
from . import _study_urlnorm_policy as origin
from ._checkpoint_codec import canonical_bytes

POLICY_PATH = "data/study-series-policy-v1.json"
ADDED_PATHS = (
    "scripts/run_study_series.py",
    "scripts/run_study_series_child.py",
    "scripts/run_study_series_session.py",
    "src/automated_phishing_detection/_stopped_study_cell_inputs.py",
    "src/automated_phishing_detection/_stopped_study_cell_process.py",
    "src/automated_phishing_detection/_stopped_study_cell_records.py",
    "src/automated_phishing_detection/_stopped_study_host.py",
    "src/automated_phishing_detection/_stopped_study_ledger.py",
    "src/automated_phishing_detection/_stopped_study_process.py",
    "src/automated_phishing_detection/_stopped_study_root.py",
    "src/automated_phishing_detection/_stopped_study_timeline_records.py",
    "src/automated_phishing_detection/_study_history_cell_inputs.py",
    "src/automated_phishing_detection/_study_history_cell_records.py",
    "src/automated_phishing_detection/_study_history_cell_science.py",
    "src/automated_phishing_detection/_study_history_external_records.py",
    "src/automated_phishing_detection/_study_history_internal_context.py",
    "src/automated_phishing_detection/_study_history_internal_science.py",
    "src/automated_phishing_detection/_study_history_snapshot_cells.py",
    "src/automated_phishing_detection/_study_history_snapshot_records.py",
    "src/automated_phishing_detection/_study_history_snapshot_sources.py",
    "src/automated_phishing_detection/_study_series_accounting_cells.py",
    "src/automated_phishing_detection/_study_series_accounting_ledger.py",
    "src/automated_phishing_detection/_study_series_accounting_records.py",
    "src/automated_phishing_detection/_study_series_admission.py",
    "src/automated_phishing_detection/_study_series_admission_child.py",
    "src/automated_phishing_detection/_study_series_admission_frame.py",
    "src/automated_phishing_detection/_study_series_admission_parent.py",
    "src/automated_phishing_detection/_study_series_adoption_authority.py",
    "src/automated_phishing_detection/_study_series_adoption_profile.py",
    "src/automated_phishing_detection/_study_series_adoption_schema.py",
    "src/automated_phishing_detection/_study_series_cell_records.py",
    "src/automated_phishing_detection/_study_series_cell_results.py",
    "src/automated_phishing_detection/_study_series_cell_runner_context.py",
    "src/automated_phishing_detection/_study_series_cell_runner_state.py",
    "src/automated_phishing_detection/_study_series_child_commands.py",
    "src/automated_phishing_detection/_study_series_child_context.py",
    "src/automated_phishing_detection/_study_series_child_input_context.py",
    "src/automated_phishing_detection/_study_series_child_operational.py",
    "src/automated_phishing_detection/_study_series_child_prefix.py",
    "src/automated_phishing_detection/_study_series_child_runtime.py",
    "src/automated_phishing_detection/_study_series_child_transport.py",
    "src/automated_phishing_detection/_study_series_components_context.py",
    "src/automated_phishing_detection/_study_series_components_science.py",
    "src/automated_phishing_detection/_study_series_execution_io.py",
    "src/automated_phishing_detection/_study_series_history_cells.py",
    "src/automated_phishing_detection/_study_series_history_context.py",
    "src/automated_phishing_detection/_study_series_history_files.py",
    "src/automated_phishing_detection/_study_series_history_origin.py",
    "src/automated_phishing_detection/_study_series_history_sources.py",
    "src/automated_phishing_detection/_study_series_index_records.py",
    "src/automated_phishing_detection/_study_series_index_refs.py",
    "src/automated_phishing_detection/_study_series_input_cells.py",
    "src/automated_phishing_detection/_study_series_input_context.py",
    "src/automated_phishing_detection/_study_series_ledger_acceptance.py",
    "src/automated_phishing_detection/_study_series_ledger_context.py",
    "src/automated_phishing_detection/_study_series_ledger_issuance.py",
    "src/automated_phishing_detection/_study_series_ledger_records.py",
    "src/automated_phishing_detection/_study_series_policy.py",
    "src/automated_phishing_detection/_study_series_prefix_records.py",
    "src/automated_phishing_detection/_study_series_prefix_validation.py",
    "src/automated_phishing_detection/_study_series_process_children.py",
    "src/automated_phishing_detection/_study_series_reduction_records.py",
    "src/automated_phishing_detection/_study_series_runner_body.py",
    "src/automated_phishing_detection/_study_series_runner_failure.py",
    "src/automated_phishing_detection/_study_series_runner_paths.py",
    "src/automated_phishing_detection/_study_series_runner_records.py",
    "src/automated_phishing_detection/_study_series_runner_state.py",
    "src/automated_phishing_detection/_study_series_runner_storage.py",
    "src/automated_phishing_detection/_study_series_session_conditions.py",
    "src/automated_phishing_detection/_study_series_session_monitor.py",
    "src/automated_phishing_detection/_study_series_session_records.py",
    "src/automated_phishing_detection/_study_series_supervisor_channel.py",
    "src/automated_phishing_detection/stopped_study_authorization.py",
    "src/automated_phishing_detection/stopped_study_cell.py",
    "src/automated_phishing_detection/stopped_study_timeline.py",
    "src/automated_phishing_detection/study_history_cell.py",
    "src/automated_phishing_detection/study_history_external.py",
    "src/automated_phishing_detection/study_history_internal.py",
    "src/automated_phishing_detection/study_history_snapshots.py",
    "src/automated_phishing_detection/study_series_accounting.py",
    "src/automated_phishing_detection/study_series_adoption.py",
    "src/automated_phishing_detection/study_series_cell.py",
    "src/automated_phishing_detection/study_series_cell_acceptance.py",
    "src/automated_phishing_detection/study_series_cell_completion.py",
    "src/automated_phishing_detection/study_series_cell_runner.py",
    "src/automated_phishing_detection/study_series_child_inputs.py",
    "src/automated_phishing_detection/study_series_components.py",
    "src/automated_phishing_detection/study_series_execution.py",
    "src/automated_phishing_detection/study_series_history.py",
    "src/automated_phishing_detection/study_series_history_index.py",
    "src/automated_phishing_detection/study_series_inputs.py",
    "src/automated_phishing_detection/study_series_ledger.py",
    "src/automated_phishing_detection/study_series_prefix.py",
    "src/automated_phishing_detection/study_series_process.py",
    "src/automated_phishing_detection/study_series_reduction.py",
    "src/automated_phishing_detection/study_series_runner.py",
    "src/automated_phishing_detection/study_series_session.py",
    "src/automated_phishing_detection/study_series_supervision.py",
)
AMENDMENT = {
    "id": "checkpointed-study-series-v1",
    "text": "Prospectively replace the single-session/no-resume commitment with one separately adopted continuation segment using the entire verified eligible attempt4 prefix and both retained sources. Final public binding, genuine operator adoption, clean pinned base-v3 code, scientific custody, sampled physical eligibility and live parent-owned admissions are required. Preserve all interrupted attempts, the original hold and all adverse results; no automatic retry, original-source reopening, fitting, threshold changes or single-session claim is permitted.",
    "representation": "publisher_url_norm_v1",
    "history_rule": "preserve_all_four_attempts_and_stopped_cell_import_only_complete_eligible_attempt4_prefix_and_both_sources",
    "continuation_rule": "one_fresh_segment2_from_verified_prefix_plus_one_through_fixed_cell125",
    "repeated_interruption_rule": "retain_stop_review_and_require_separately_implemented_and_adopted_next_segment",
    "disclosure_rule": "prospective_only_no_replacement_of_original_results_disclose_exposure_and_session_confounding",
}
PRESERVATION = {
    "source_scope": "every_original_entry_byte_identical_only_literal_reviewed_additions",
    "scientific_components": "original_and_current_pins_separate_scientific_projections_equal",
    "model_bindings": "unchanged_all_artifacts_seeds_thresholds_and_intervals_no_retraining",
    "runtime": "unchanged_original_host_environment_and_base_v3_runtime_pins",
    "schedule": "unchanged_125_cells_controls_60_seconds_request_deadline_2000_milliseconds_and_request_counts",
    "reducers": "unchanged_populations_quarantine_hypotheses_and_reducers",
    "original_h2_audit": "preserve_original_failure_28_of_252",
}


def policy_projection():
    return {
        "schema_version": 1,
        "policy_id": "study-series-policy-v1",
        "status": "specified_for_explicit_adoption",
        "base_contract": {
            "id": "execution-binding-v3",
            "sha256": original.CONTRACT_SHA256,
        },
        "origin_policy_sha256": sha256(origin.policy_bytes()).hexdigest(),
        "amendment": dict(AMENDMENT),
        "preservation": dict(PRESERVATION),
        "session_requirements": dict(original.SESSION_REQUIREMENTS),
        "protective_deadlines_seconds": dict(original.DEADLINES),
        "permitted_added_paths": list(ADDED_PATHS),
        "scripts": {
            "supervisor": "scripts/run_study_series_session.py",
            "root": "scripts/run_study_series.py",
            "child": "scripts/run_study_series_child.py",
        },
        "admission_roles": ["service", "client"],
        "trust_boundary": "actual_decision_records_under_trusted_operator_not_cryptographic_consent",
        "legacy_readiness": False,
    }


def policy_bytes():
    return canonical_bytes(policy_projection())
